//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.31 at 06:56:01 AM EDT 
//


package example;

public class AuthorizationResponse {

    protected String code;
    protected String message;
    protected String transactionId;
    protected Long authSeq;
    protected String approvalCode;

    public String getCode() { return code; }
    public void setCode(String value) { this.code = value; }


    public String getMessage() { return message; }
    public void setMessage(String value) { this.message = value; }

    public String getTransactionId() { return transactionId; }
    public void setTransactionId(String value) { this.transactionId = value; }

    public Long getAuthSeq() { return authSeq; }
    public void setAuthSeq(Long value) { this.authSeq = value; }

    public String getApprovalCode() { return approvalCode; }
    public void setApprovalCode(String value) { this.approvalCode = value; }

}
