//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.31 at 06:56:01 AM EDT 
//


package com.bluetarp.authorization.api.v1.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuthorizationRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuthorizationRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="merchant-number" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="client-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="client-username" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="transaction-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="purchaser-with-token" type="{http://api.bluetarp.com/ns/1.0}PurchaserWithToken"/>
 *           &lt;element name="purchaser" type="{http://api.bluetarp.com/ns/1.0}PurchaserWithCard"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="sale" type="{http://api.bluetarp.com/ns/1.0}Sale"/>
 *           &lt;element name="credit" type="{http://api.bluetarp.com/ns/1.0}Credit"/>
 *           &lt;element name="deposit-hold" type="{http://api.bluetarp.com/ns/1.0}DepositHold"/>
 *           &lt;element name="deposit-collect" type="{http://api.bluetarp.com/ns/1.0}DepositCollect"/>
 *           &lt;element name="void" type="{http://api.bluetarp.com/ns/1.0}Void"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuthorizationRequest", propOrder = {
    "merchantNumber",
    "clientId",
    "clientUsername",
    "transactionId",
    "purchaserWithToken",
    "purchaser",
    "sale",
    "credit",
    "depositHold",
    "depositCollect",
    "_void"
})
public class AuthorizationRequest {

    @XmlElement(name = "merchant-number")
    protected long merchantNumber;
    @XmlElement(name = "client-id", required = true)
    protected String clientId;
    @XmlElement(name = "client-username")
    protected String clientUsername;
    @XmlElement(name = "transaction-id", required = true)
    protected String transactionId;
    @XmlElement(name = "purchaser-with-token")
    protected PurchaserWithToken purchaserWithToken;
    protected PurchaserWithCard purchaser;
    protected Sale sale;
    protected Credit credit;
    @XmlElement(name = "deposit-hold")
    protected DepositHold depositHold;
    @XmlElement(name = "deposit-collect")
    protected DepositCollect depositCollect;
    @XmlElement(name = "void")
    protected Void _void;

    /**
     * Gets the value of the merchantNumber property.
     * 
     */
    public long getMerchantNumber() {
        return merchantNumber;
    }

    /**
     * Sets the value of the merchantNumber property.
     * 
     */
    public void setMerchantNumber(long value) {
        this.merchantNumber = value;
    }

    /**
     * Gets the value of the clientId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the clientUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientUsername() {
        return clientUsername;
    }

    /**
     * Sets the value of the clientUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientUsername(String value) {
        this.clientUsername = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the purchaserWithToken property.
     * 
     * @return
     *     possible object is
     *     {@link PurchaserWithToken }
     *     
     */
    public PurchaserWithToken getPurchaserWithToken() {
        return purchaserWithToken;
    }

    /**
     * Sets the value of the purchaserWithToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchaserWithToken }
     *     
     */
    public void setPurchaserWithToken(PurchaserWithToken value) {
        this.purchaserWithToken = value;
    }

    /**
     * Gets the value of the purchaser property.
     * 
     * @return
     *     possible object is
     *     {@link PurchaserWithCard }
     *     
     */
    public PurchaserWithCard getPurchaser() {
        return purchaser;
    }

    /**
     * Sets the value of the purchaser property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchaserWithCard }
     *     
     */
    public void setPurchaser(PurchaserWithCard value) {
        this.purchaser = value;
    }

    /**
     * Gets the value of the sale property.
     * 
     * @return
     *     possible object is
     *     {@link Sale }
     *     
     */
    public Sale getSale() {
        return sale;
    }

    /**
     * Sets the value of the sale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sale }
     *     
     */
    public void setSale(Sale value) {
        this.sale = value;
    }

    /**
     * Gets the value of the credit property.
     * 
     * @return
     *     possible object is
     *     {@link Credit }
     *     
     */
    public Credit getCredit() {
        return credit;
    }

    /**
     * Sets the value of the credit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Credit }
     *     
     */
    public void setCredit(Credit value) {
        this.credit = value;
    }

    /**
     * Gets the value of the depositHold property.
     * 
     * @return
     *     possible object is
     *     {@link DepositHold }
     *     
     */
    public DepositHold getDepositHold() {
        return depositHold;
    }

    /**
     * Sets the value of the depositHold property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepositHold }
     *     
     */
    public void setDepositHold(DepositHold value) {
        this.depositHold = value;
    }

    /**
     * Gets the value of the depositCollect property.
     * 
     * @return
     *     possible object is
     *     {@link DepositCollect }
     *     
     */
    public DepositCollect getDepositCollect() {
        return depositCollect;
    }

    /**
     * Sets the value of the depositCollect property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepositCollect }
     *     
     */
    public void setDepositCollect(DepositCollect value) {
        this.depositCollect = value;
    }

    /**
     * Gets the value of the void property.
     * 
     * @return
     *     possible object is
     *     {@link Void }
     *     
     */
    public Void getVoid() {
        return _void;
    }

    /**
     * Sets the value of the void property.
     * 
     * @param value
     *     allowed object is
     *     {@link Void }
     *     
     */
    public void setVoid(Void value) {
        this._void = value;
    }

}
