//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.31 at 06:56:01 AM EDT 
//


package com.bluetarp.authorization.api.v1.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BlueTarpAuthorization complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BlueTarpAuthorization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="authorization-request" type="{http://api.bluetarp.com/ns/1.0}AuthorizationRequest"/>
 *         &lt;element name="authorization-response" type="{http://api.bluetarp.com/ns/1.0}AuthorizationResponse"/>
 *         &lt;element name="customer-response" type="{http://api.bluetarp.com/ns/1.0}CustomerResponse"/>
 *         &lt;element name="transaction-response" type="{http://api.bluetarp.com/ns/1.0}TransactionResponse"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BlueTarpAuthorization", propOrder = {
    "authorizationRequest",
    "authorizationResponse",
    "customerResponse",
    "transactionResponse"
})
public class BlueTarpAuthorization {

    @XmlElement(name = "authorization-request")
    protected AuthorizationRequest authorizationRequest;
    @XmlElement(name = "authorization-response")
    protected AuthorizationResponse authorizationResponse;
    @XmlElement(name = "customer-response")
    protected CustomerResponse customerResponse;
    @XmlElement(name = "transaction-response")
    protected TransactionResponse transactionResponse;

    /**
     * Gets the value of the authorizationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorizationRequest }
     *     
     */
    public AuthorizationRequest getAuthorizationRequest() {
        return authorizationRequest;
    }

    /**
     * Sets the value of the authorizationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorizationRequest }
     *     
     */
    public void setAuthorizationRequest(AuthorizationRequest value) {
        this.authorizationRequest = value;
    }

    /**
     * Gets the value of the authorizationResponse property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorizationResponse }
     *     
     */
    public AuthorizationResponse getAuthorizationResponse() {
        return authorizationResponse;
    }

    /**
     * Sets the value of the authorizationResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorizationResponse }
     *     
     */
    public void setAuthorizationResponse(AuthorizationResponse value) {
        this.authorizationResponse = value;
    }

    /**
     * Gets the value of the customerResponse property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerResponse }
     *     
     */
    public CustomerResponse getCustomerResponse() {
        return customerResponse;
    }

    /**
     * Sets the value of the customerResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerResponse }
     *     
     */
    public void setCustomerResponse(CustomerResponse value) {
        this.customerResponse = value;
    }

    /**
     * Gets the value of the transactionResponse property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionResponse }
     *     
     */
    public TransactionResponse getTransactionResponse() {
        return transactionResponse;
    }

    /**
     * Sets the value of the transactionResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionResponse }
     *     
     */
    public void setTransactionResponse(TransactionResponse value) {
        this.transactionResponse = value;
    }

}
