//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.31 at 06:56:01 AM EDT 
//


package com.bluetarp.authorization.api.v1.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bluetarp.authorization.api.v1.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BluetarpAuthorization_QNAME = new QName("http://api.bluetarp.com/ns/1.0", "bluetarp-authorization");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bluetarp.authorization.api.v1.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerResponse }
     * 
     */
    public CustomerResponse createCustomerResponse() {
        return new CustomerResponse();
    }

    /**
     * Create an instance of {@link TransactionResponse }
     * 
     */
    public TransactionResponse createTransactionResponse() {
        return new TransactionResponse();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link BlueTarpAuthorization }
     * 
     */
    public BlueTarpAuthorization createBlueTarpAuthorization() {
        return new BlueTarpAuthorization();
    }

    /**
     * Create an instance of {@link PurchaserWithToken }
     * 
     */
    public PurchaserWithToken createPurchaserWithToken() {
        return new PurchaserWithToken();
    }

    /**
     * Create an instance of {@link AuthorizationResponse }
     * 
     */
    public AuthorizationResponse createAuthorizationResponse() {
        return new AuthorizationResponse();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link AuthorizationRequest }
     * 
     */
    public AuthorizationRequest createAuthorizationRequest() {
        return new AuthorizationRequest();
    }

    /**
     * Create an instance of {@link PurchaserWithCard }
     * 
     */
    public PurchaserWithCard createPurchaserWithCard() {
        return new PurchaserWithCard();
    }

    /**
     * Create an instance of {@link Void }
     * 
     */
    public Void createVoid() {
        return new Void();
    }

    /**
     * Create an instance of {@link Credit }
     * 
     */
    public Credit createCredit() {
        return new Credit();
    }

    /**
     * Create an instance of {@link DepositHold }
     * 
     */
    public DepositHold createDepositHold() {
        return new DepositHold();
    }

    /**
     * Create an instance of {@link DepositCollect }
     * 
     */
    public DepositCollect createDepositCollect() {
        return new DepositCollect();
    }

    /**
     * Create an instance of {@link Purchaser }
     * 
     */
    public Purchaser createPurchaser() {
        return new Purchaser();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Sale }
     * 
     */
    public Sale createSale() {
        return new Sale();
    }

    /**
     * Create an instance of {@link CustomerResponse.Customers }
     * 
     */
    public CustomerResponse.Customers createCustomerResponseCustomers() {
        return new CustomerResponse.Customers();
    }

    /**
     * Create an instance of {@link TransactionResponse.Transactions }
     * 
     */
    public TransactionResponse.Transactions createTransactionResponseTransactions() {
        return new TransactionResponse.Transactions();
    }

    /**
     * Create an instance of {@link Customer.Purchasers }
     * 
     */
    public Customer.Purchasers createCustomerPurchasers() {
        return new Customer.Purchasers();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlueTarpAuthorization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluetarp.com/ns/1.0", name = "bluetarp-authorization")
    public JAXBElement<BlueTarpAuthorization> createBluetarpAuthorization(BlueTarpAuthorization value) {
        return new JAXBElement<BlueTarpAuthorization>(_BluetarpAuthorization_QNAME, BlueTarpAuthorization.class, null, value);
    }

}
