//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.31 at 06:56:01 AM EDT 
//


package com.bluetarp.authorization.api.v1.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Status.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Status">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Active"/>
 *     &lt;enumeration value="Chargeoff"/>
 *     &lt;enumeration value="Closed"/>
 *     &lt;enumeration value="Pending"/>
 *     &lt;enumeration value="Pre-Chargeoff"/>
 *     &lt;enumeration value="Suspended"/>
 *     &lt;enumeration value="Temp Stop"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Status")
@XmlEnum
public enum Status {

    @XmlEnumValue("Active")
    ACTIVE("Active"),
    @XmlEnumValue("Chargeoff")
    CHARGEOFF("Chargeoff"),
    @XmlEnumValue("Closed")
    CLOSED("Closed"),
    @XmlEnumValue("Pending")
    PENDING("Pending"),
    @XmlEnumValue("Pre-Chargeoff")
    PRE_CHARGEOFF("Pre-Chargeoff"),
    @XmlEnumValue("Suspended")
    SUSPENDED("Suspended"),
    @XmlEnumValue("Temp Stop")
    TEMP_STOP("Temp Stop");
    private final String value;

    Status(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Status fromValue(String v) {
        for (Status c: Status.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
