//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.31 at 06:56:01 AM EDT 
//


package com.bluetarp.authorization.api.v1.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Transaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Transaction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="authseq-number" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="customer" type="{http://api.bluetarp.com/ns/1.0}Customer"/>
 *         &lt;element name="job-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="invoice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="original-invoice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Transaction", propOrder = {
    "authseqNumber",
    "customer",
    "jobCode",
    "invoice",
    "originalInvoice",
    "amount"
})
public class Transaction {
    @XmlElement(name = "auth-seq")
    protected long authseqNumber;
    @XmlElement(required = true)
    protected Customer customer;
    @XmlElement(name = "job-code", required = true)
    protected String jobCode;
    @XmlElement(required = true)
    protected String invoice;
    @XmlElement(name = "original-invoice", required = true)
    protected String originalInvoice;
    protected double amount;

    /**
     * Gets the value of the authseqNumber property.
     * 
     */
    public long getAuthseqNumber() {
        return authseqNumber;
    }

    /**
     * Sets the value of the authseqNumber property.
     * 
     */
    public void setAuthseqNumber(long value) {
        this.authseqNumber = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link Customer }
     *     
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Customer }
     *     
     */
    public void setCustomer(Customer value) {
        this.customer = value;
    }

    /**
     * Gets the value of the jobCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobCode() {
        return jobCode;
    }

    /**
     * Sets the value of the jobCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobCode(String value) {
        this.jobCode = value;
    }

    /**
     * Gets the value of the invoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoice() {
        return invoice;
    }

    /**
     * Sets the value of the invoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoice(String value) {
        this.invoice = value;
    }

    /**
     * Gets the value of the originalInvoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalInvoice() {
        return originalInvoice;
    }

    /**
     * Sets the value of the originalInvoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalInvoice(String value) {
        this.originalInvoice = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public double getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(double value) {
        this.amount = value;
    }

}
